import type { SuggestionScope } from "../types";

export interface DebugPrPreset {
  id: string;
  label: string;
  owner: string;
  repo: string;
  prNumber: number;
  scope?: SuggestionScope[];
  maxComments?: number;
}

// Autogenerated by backend/scripts/export_pr_mocks.py
export const DEBUG_PR_PRESETS: DebugPrPreset[] = [
  {
    id: "preset-1",
    label: "IlyaMr11/MIApp#20",
    owner: "IlyaMr11",
    repo: "MIApp",
    prNumber: 20,
    scope: ["security", "bugs"],
    maxComments: 40,
  },
  {
    id: "preset-2",
    label: "IlyaMr11/MIApp#21",
    owner: "IlyaMr11",
    repo: "MIApp",
    prNumber: 21,
    scope: ["security", "bugs"],
    maxComments: 40,
  },
  {
    id: "preset-3",
    label: "IlyaMr11/MIApp#23",
    owner: "IlyaMr11",
    repo: "MIApp",
    prNumber: 23,
    scope: ["security", "bugs"],
    maxComments: 40,
  },
];
